/// Each entry is (glyph, name, category).
/// The name field is used for search matching.
pub static EMOJI_LIST: &[(&str, &str, &str)] = &[
    // ── Smileys & Emotion ─────────────────────────────────────────────────
    ("😀", "grinning face", "Smileys"),
    ("😁", "beaming face with smiling eyes", "Smileys"),
    ("😂", "face with tears of joy", "Smileys"),
    ("🤣", "rolling on the floor laughing", "Smileys"),
    ("😃", "smiling face with big eyes", "Smileys"),
    ("😄", "smiling face with smiling eyes", "Smileys"),
    ("😅", "smiling face with sweat", "Smileys"),
    ("😆", "grinning squinting face", "Smileys"),
    ("😇", "smiling face with halo", "Smileys"),
    ("🥰", "smiling face with hearts", "Smileys"),
    ("😉", "winking face", "Smileys"),
    ("😊", "smiling face with smiling eyes soft", "Smileys"),
    ("😘", "face blowing a kiss", "Smileys"),
    ("😗", "kissing face", "Smileys"),
    ("😙", "kissing face with smiling eyes", "Smileys"),
    ("😚", "kissing face with closed eyes", "Smileys"),
    ("😋", "face savoring food yum", "Smileys"),
    ("😛", "face with tongue", "Smileys"),
    ("😜", "winking face with tongue", "Smileys"),
    ("🤪", "zany face", "Smileys"),
    ("😝", "squinting face with tongue", "Smileys"),
    ("🤑", "money-mouth face", "Smileys"),
    ("🤗", "hugging face", "Smileys"),
    ("🤫", "shushing face", "Smileys"),
    ("🤔", "thinking face", "Smileys"),
    ("🤐", "zipper-mouth face", "Smileys"),
    ("🤨", "face with raised eyebrow", "Smileys"),
    ("😐", "neutral face", "Smileys"),
    ("😑", "expressionless face", "Smileys"),
    ("😶", "face without mouth", "Smileys"),
    ("🙂", "slightly smiling face", "Smileys"),
    ("🙃", "upside-down face", "Smileys"),
    ("🤥", "lying face", "Smileys"),
    ("😔", "pensive face", "Smileys"),
    ("😕", "confused face", "Smileys"),
    ("🤭", "face with hand over mouth", "Smileys"),
    ("🤫", "shushing face quiet", "Smileys"),
    ("😲", "astonished face", "Smileys"),
    ("🙁", "slightly frowning face", "Smileys"),
    ("😮", "face with open mouth", "Smileys"),
    ("😯", "hushed face", "Smileys"),
    ("😦", "frowning face with open mouth", "Smileys"),
    ("😧", "anguished face", "Smileys"),
    ("😨", "fearful face", "Smileys"),
    ("😰", "anxious face with sweat", "Smileys"),
    ("😥", "sad but relieved face", "Smileys"),
    ("😢", "crying face", "Smileys"),
    ("😭", "loudly crying face", "Smileys"),
    ("😱", "face screaming in fear", "Smileys"),
    ("😖", "confounded face", "Smileys"),
    ("😣", "persevering face", "Smileys"),
    ("😞", "disappointed face", "Smileys"),
    ("😓", "downcast face with sweat", "Smileys"),
    ("😩", "weary face", "Smileys"),
    ("😫", "tired face", "Smileys"),
    ("🥱", "yawning face", "Smileys"),
    ("😤", "face with steam from nose", "Smileys"),
    ("😡", "pouting face angry", "Smileys"),
    ("😠", "angry face", "Smileys"),
    ("🤬", "face with symbols on mouth", "Smileys"),
    ("😈", "smiling face with horns devil", "Smileys"),
    ("👿", "angry face with horns", "Smileys"),
    ("💀", "skull", "Smileys"),
    ("☠️", "skull and crossbones", "Smileys"),
    ("💩", "pile of poo", "Smileys"),
    ("🤡", "clown face", "Smileys"),
    ("👻", "ghost", "Smileys"),
    ("👽", "alien", "Smileys"),
    ("🤖", "robot", "Smileys"),
    ("😺", "grinning cat", "Smileys"),
    ("😸", "grinning cat with smiling eyes", "Smileys"),
    ("😹", "cat with tears of joy", "Smileys"),
    ("😻", "smiling cat with heart-eyes", "Smileys"),
    ("😼", "cat with wry smile", "Smileys"),
    ("😽", "kissing cat", "Smileys"),
    ("🙀", "weary cat", "Smileys"),
    ("😿", "crying cat", "Smileys"),
    ("😾", "pouting cat", "Smileys"),
    ("🙈", "see-no-evil monkey", "Smileys"),
    ("🙉", "hear-no-evil monkey", "Smileys"),
    ("🙊", "speak-no-evil monkey", "Smileys"),
    ("🤓", "nerd face", "Smileys"),
    ("😎", "smiling face with sunglasses", "Smileys"),
    ("🥸", "disguised face", "Smileys"),
    ("🤩", "star-struck", "Smileys"),
    ("🥳", "partying face", "Smileys"),
    ("😏", "smirking face", "Smileys"),
    ("😒", "unamused face", "Smileys"),
    ("😞", "disappointed face sad", "Smileys"),
    ("😟", "worried face", "Smileys"),
    ("🤢", "nauseated face sick", "Smileys"),
    ("🤧", "sneezing face", "Smileys"),
    ("🥵", "hot face", "Smileys"),
    ("🥶", "cold face", "Smileys"),
    ("🥴", "woozy face", "Smileys"),
    ("😵", "dizzy face", "Smileys"),
    ("🤯", "exploding head", "Smileys"),
    ("🤠", "cowboy hat face", "Smileys"),
    ("🥺", "pleading face", "Smileys"),
    ("😬", "grimacing face", "Smileys"),
    ("🙄", "face with rolling eyes", "Smileys"),
    ("😴", "sleeping face", "Smileys"),
    ("🤒", "face with thermometer sick", "Smileys"),
    ("🤕", "face with head-bandage", "Smileys"),
    ("🤑", "money mouth", "Smileys"),
    ("😷", "face with medical mask", "Smileys"),
    ("🤮", "face vomiting", "Smileys"),
    ("🥹", "face holding back tears", "Smileys"),
    ("🫠", "melting face", "Smileys"),
    ("🫥", "dotted line face", "Smileys"),
    ("🫨", "shaking face", "Smileys"),
    // ── People & Body ─────────────────────────────────────────────────────
    ("👋", "waving hand", "People"),
    ("🤚", "raised back of hand", "People"),
    ("✋", "raised hand", "People"),
    ("🖖", "vulcan salute", "People"),
    ("👌", "ok hand", "People"),
    ("✌️", "victory hand", "People"),
    ("🤞", "crossed fingers", "People"),
    ("🤟", "love-you gesture", "People"),
    ("🤘", "sign of the horns", "People"),
    ("🤙", "call me hand", "People"),
    ("👈", "backhand index pointing left", "People"),
    ("👉", "backhand index pointing right", "People"),
    ("👆", "backhand index pointing up", "People"),
    ("🖕", "middle finger", "People"),
    ("👇", "backhand index pointing down", "People"),
    ("☝️", "index pointing up", "People"),
    ("👍", "thumbs up like", "People"),
    ("👎", "thumbs down dislike", "People"),
    ("✊", "raised fist", "People"),
    ("👊", "oncoming fist punch", "People"),
    ("🤛", "left-facing fist", "People"),
    ("🤜", "right-facing fist", "People"),
    ("👏", "clapping hands", "People"),
    ("🙌", "raising hands", "People"),
    ("👐", "open hands", "People"),
    ("🤲", "palms up together", "People"),
    ("🤝", "handshake", "People"),
    ("🙏", "folded hands please pray", "People"),
    ("✍️", "writing hand", "People"),
    ("💅", "nail polish", "People"),
    ("🤳", "selfie", "People"),
    ("💪", "flexed biceps strong", "People"),
    ("🦵", "leg", "People"),
    ("🦶", "foot", "People"),
    ("👂", "ear", "People"),
    ("👃", "nose", "People"),
    ("🧠", "brain", "People"),
    ("👀", "eyes", "People"),
    ("👁️", "eye", "People"),
    ("👅", "tongue", "People"),
    ("👄", "mouth lips", "People"),
    ("👶", "baby", "People"),
    ("👦", "boy", "People"),
    ("👧", "girl", "People"),
    ("🧒", "child", "People"),
    ("👨", "man", "People"),
    ("👩", "woman", "People"),
    ("🧑", "person", "People"),
    ("👴", "old man", "People"),
    ("👵", "old woman", "People"),
    ("👮", "police officer", "People"),
    ("💂", "guard", "People"),
    ("🕵️", "detective", "People"),
    ("👷", "construction worker", "People"),
    ("🤴", "prince", "People"),
    ("👸", "princess", "People"),
    ("👲", "person with skullcap", "People"),
    ("🧕", "woman with headscarf", "People"),
    ("🤵", "person in tuxedo", "People"),
    ("👰", "person with veil bride", "People"),
    ("🦸", "superhero", "People"),
    ("🦹", "supervillain", "People"),
    ("🧙", "mage wizard", "People"),
    ("🧚", "fairy", "People"),
    ("🧛", "vampire", "People"),
    ("🧟", "zombie", "People"),
    ("🧞", "genie", "People"),
    ("🧜", "merperson mermaid", "People"),
    ("🧝", "elf", "People"),
    ("🤶", "mrs claus", "People"),
    ("🎅", "santa claus", "People"),
    ("🦊", "fox", "People"),
    // ── Animals ───────────────────────────────────────────────────────────
    ("🐶", "dog face", "Animals"),
    ("🐱", "cat face", "Animals"),
    ("🐭", "mouse face", "Animals"),
    ("🐹", "hamster", "Animals"),
    ("🐰", "rabbit face", "Animals"),
    ("🦊", "fox face", "Animals"),
    ("🐻", "bear", "Animals"),
    ("🐼", "panda", "Animals"),
    ("🐨", "koala", "Animals"),
    ("🐯", "tiger face", "Animals"),
    ("🦁", "lion", "Animals"),
    ("🐮", "cow face", "Animals"),
    ("🐷", "pig face", "Animals"),
    ("🐸", "frog", "Animals"),
    ("🐵", "monkey face", "Animals"),
    ("🐔", "chicken", "Animals"),
    ("🐧", "penguin", "Animals"),
    ("🐦", "bird", "Animals"),
    ("🐤", "baby chick", "Animals"),
    ("🦆", "duck", "Animals"),
    ("🦅", "eagle", "Animals"),
    ("🦉", "owl", "Animals"),
    ("🦇", "bat", "Animals"),
    ("🐺", "wolf", "Animals"),
    ("🐗", "boar", "Animals"),
    ("🐴", "horse face", "Animals"),
    ("🦄", "unicorn", "Animals"),
    ("🐝", "honeybee", "Animals"),
    ("🦋", "butterfly", "Animals"),
    ("🐌", "snail", "Animals"),
    ("🐞", "lady beetle ladybug", "Animals"),
    ("🐍", "snake", "Animals"),
    ("🐢", "turtle", "Animals"),
    ("🦎", "lizard", "Animals"),
    ("🦕", "sauropod dinosaur", "Animals"),
    ("🦖", "t-rex dinosaur", "Animals"),
    ("🐙", "octopus", "Animals"),
    ("🐠", "tropical fish", "Animals"),
    ("🐟", "fish", "Animals"),
    ("🐬", "dolphin", "Animals"),
    ("🐳", "spouting whale", "Animals"),
    ("🦈", "shark", "Animals"),
    ("🐋", "whale", "Animals"),
    ("🐊", "crocodile", "Animals"),
    ("🦓", "zebra", "Animals"),
    ("🦒", "giraffe", "Animals"),
    ("🦘", "kangaroo", "Animals"),
    ("🦙", "llama", "Animals"),
    ("🐘", "elephant", "Animals"),
    ("🦏", "rhinoceros", "Animals"),
    ("🦛", "hippopotamus", "Animals"),
    ("🐐", "goat", "Animals"),
    ("🐑", "ewe sheep", "Animals"),
    ("🦜", "parrot", "Animals"),
    ("🦚", "peacock", "Animals"),
    ("🦩", "flamingo", "Animals"),
    ("🦢", "swan", "Animals"),
    ("🐇", "rabbit", "Animals"),
    ("🐿️", "chipmunk", "Animals"),
    ("🦔", "hedgehog", "Animals"),
    ("🐾", "paw prints", "Animals"),
    // ── Food & Drink ──────────────────────────────────────────────────────
    ("🍇", "grapes", "Food"),
    ("🍈", "melon", "Food"),
    ("🍉", "watermelon", "Food"),
    ("🍊", "tangerine orange", "Food"),
    ("🍋", "lemon", "Food"),
    ("🍌", "banana", "Food"),
    ("🍍", "pineapple", "Food"),
    ("🥭", "mango", "Food"),
    ("🍎", "red apple", "Food"),
    ("🍏", "green apple", "Food"),
    ("🍐", "pear", "Food"),
    ("🍑", "peach", "Food"),
    ("🍒", "cherries", "Food"),
    ("🍓", "strawberry", "Food"),
    ("🫐", "blueberries", "Food"),
    ("🥝", "kiwi fruit", "Food"),
    ("🍅", "tomato", "Food"),
    ("🥦", "broccoli", "Food"),
    ("🍆", "eggplant aubergine", "Food"),
    ("🥑", "avocado", "Food"),
    ("🌽", "ear of corn maize", "Food"),
    ("🥒", "cucumber", "Food"),
    ("🧄", "garlic", "Food"),
    ("🧅", "onion", "Food"),
    ("🍄", "mushroom", "Food"),
    ("🥜", "peanuts", "Food"),
    ("🌾", "sheaf of rice wheat", "Food"),
    ("🌶️", "hot pepper chili", "Food"),
    ("🥕", "carrot", "Food"),
    ("🥔", "potato", "Food"),
    ("🥗", "salad", "Food"),
    ("🍟", "french fries", "Food"),
    ("🍕", "pizza", "Food"),
    ("🍔", "hamburger burger", "Food"),
    ("🌭", "hot dog", "Food"),
    ("🥪", "sandwich", "Food"),
    ("🧇", "waffle", "Food"),
    ("🍳", "cooking egg", "Food"),
    ("🥯", "bagel", "Food"),
    ("🍱", "bento box", "Food"),
    ("🍜", "steaming bowl noodles", "Food"),
    ("🍣", "sushi", "Food"),
    ("🍦", "soft ice cream", "Food"),
    ("🍧", "shaved ice", "Food"),
    ("🍨", "ice cream", "Food"),
    ("🍰", "shortcake", "Food"),
    ("🎂", "birthday cake", "Food"),
    ("🧁", "cupcake", "Food"),
    ("🍮", "custard pudding", "Food"),
    ("🍭", "lollipop candy", "Food"),
    ("🍬", "candy", "Food"),
    ("🍫", "chocolate bar", "Food"),
    ("🍿", "popcorn", "Food"),
    ("🥐", "croissant", "Food"),
    ("🥖", "baguette bread", "Food"),
    ("🧀", "cheese wedge", "Food"),
    ("🥩", "cut of meat steak", "Food"),
    ("🥓", "bacon", "Food"),
    ("🍳", "egg fried", "Food"),
    ("🫕", "fondue", "Food"),
    ("🍲", "pot of food", "Food"),
    ("🍺", "beer mug", "Food"),
    ("🍻", "clinking beer mugs", "Food"),
    ("☕", "hot beverage coffee", "Food"),
    ("🍵", "teacup without handle tea", "Food"),
    ("🧋", "bubble tea boba", "Food"),
    ("🍶", "sake", "Food"),
    ("🍷", "wine glass", "Food"),
    ("🍸", "cocktail glass", "Food"),
    ("🍹", "tropical drink", "Food"),
    ("🧃", "beverage box juice", "Food"),
    ("🥤", "cup with straw", "Food"),
    ("🧊", "ice cube", "Food"),
    ("🫖", "teapot", "Food"),
    // ── Travel & Places ───────────────────────────────────────────────────
    ("🌍", "globe europe africa", "Travel"),
    ("🌎", "globe americas", "Travel"),
    ("🌏", "globe asia australia", "Travel"),
    ("🌐", "globe with meridians", "Travel"),
    ("🗺️", "world map", "Travel"),
    ("🏔️", "snow-capped mountain", "Travel"),
    ("⛰️", "mountain", "Travel"),
    ("🌋", "volcano", "Travel"),
    ("🗻", "mount fuji", "Travel"),
    ("🏕️", "camping", "Travel"),
    ("🏖️", "beach with umbrella", "Travel"),
    ("🏠", "house", "Travel"),
    ("🏡", "house with garden", "Travel"),
    ("🏢", "office building", "Travel"),
    ("🏦", "bank", "Travel"),
    ("🏨", "hotel", "Travel"),
    ("🏪", "convenience store", "Travel"),
    ("🏫", "school", "Travel"),
    ("⛪", "church", "Travel"),
    ("🕌", "mosque", "Travel"),
    ("⛩️", "shinto shrine", "Travel"),
    ("🕍", "synagogue", "Travel"),
    ("⛲", "fountain", "Travel"),
    ("⛺", "tent camping", "Travel"),
    ("🌁", "foggy", "Travel"),
    ("🌃", "night with stars", "Travel"),
    ("🏞️", "national park", "Travel"),
    ("🌄", "sunrise over mountains", "Travel"),
    ("🌅", "sunrise", "Travel"),
    ("🌆", "cityscape at dusk", "Travel"),
    ("🌇", "sunset", "Travel"),
    ("🌉", "bridge at night", "Travel"),
    ("🚀", "rocket", "Travel"),
    ("🛸", "flying saucer ufo", "Travel"),
    ("🚕", "taxi", "Travel"),
    ("🚗", "automobile car", "Travel"),
    ("🚌", "bus", "Travel"),
    ("🚲", "bicycle bike", "Travel"),
    ("✈️", "airplane plane", "Travel"),
    ("🚂", "locomotive train", "Travel"),
    ("🚢", "ship boat", "Travel"),
    ("🚁", "helicopter", "Travel"),
    ("⛵", "sailboat", "Travel"),
    ("🛺", "auto rickshaw", "Travel"),
    ("🛵", "motor scooter", "Travel"),
    ("🏍️", "motorcycle", "Travel"),
    ("🚦", "vertical traffic light", "Travel"),
    ("🗼", "tokyo tower", "Travel"),
    ("🗽", "statue of liberty", "Travel"),
    ("🗿", "moai", "Travel"),
    ("🏯", "japanese castle", "Travel"),
    ("🏰", "castle", "Travel"),
    // ── Activities ────────────────────────────────────────────────────────
    ("⚽", "soccer ball football", "Activities"),
    ("🏀", "basketball", "Activities"),
    ("🏈", "american football", "Activities"),
    ("⚾", "baseball", "Activities"),
    ("🎾", "tennis", "Activities"),
    ("🏐", "volleyball", "Activities"),
    ("🏉", "rugby football", "Activities"),
    ("🎱", "pool 8 ball billiards", "Activities"),
    ("🏓", "ping pong table tennis", "Activities"),
    ("🏸", "badminton", "Activities"),
    ("🥅", "goal net", "Activities"),
    ("🎿", "skis skiing", "Activities"),
    ("🛷", "sled", "Activities"),
    ("🏆", "trophy award", "Activities"),
    ("🥇", "1st place medal gold", "Activities"),
    ("🥈", "2nd place medal silver", "Activities"),
    ("🥉", "3rd place medal bronze", "Activities"),
    ("🏅", "sports medal", "Activities"),
    ("🎫", "ticket", "Activities"),
    ("🎨", "artist palette art", "Activities"),
    ("🎬", "clapper board movie", "Activities"),
    ("🎤", "microphone sing", "Activities"),
    ("🎧", "headphone music", "Activities"),
    ("🎥", "movie camera", "Activities"),
    ("📷", "camera photo", "Activities"),
    ("🎹", "musical keyboard piano", "Activities"),
    ("🎸", "guitar music", "Activities"),
    ("🎺", "trumpet", "Activities"),
    ("🥁", "drum music", "Activities"),
    ("🎻", "violin", "Activities"),
    ("🎲", "game die dice", "Activities"),
    ("🎮", "video game controller", "Activities"),
    ("🕹️", "joystick game", "Activities"),
    ("🃏", "joker card", "Activities"),
    ("🎯", "bullseye target", "Activities"),
    ("🎳", "bowling", "Activities"),
    ("🎰", "slot machine", "Activities"),
    ("🧩", "puzzle piece", "Activities"),
    ("🎭", "performing arts theatre", "Activities"),
    ("🎪", "circus tent", "Activities"),
    ("🎢", "roller coaster", "Activities"),
    ("🎡", "ferris wheel", "Activities"),
    ("🎠", "carousel horse", "Activities"),
    // ── Objects ───────────────────────────────────────────────────────────
    ("📱", "mobile phone cell", "Objects"),
    ("💻", "laptop computer", "Objects"),
    ("⌨️", "keyboard", "Objects"),
    ("🖥️", "desktop computer", "Objects"),
    ("🖱️", "computer mouse", "Objects"),
    ("💾", "floppy disk", "Objects"),
    ("💿", "optical disk cd", "Objects"),
    ("📀", "dvd", "Objects"),
    ("☎️", "telephone", "Objects"),
    ("📞", "telephone receiver", "Objects"),
    ("📟", "pager", "Objects"),
    ("🔋", "battery", "Objects"),
    ("🔌", "electric plug", "Objects"),
    ("💡", "light bulb idea", "Objects"),
    ("🔦", "flashlight torch", "Objects"),
    ("🕯️", "candle", "Objects"),
    ("📁", "file folder", "Objects"),
    ("📂", "open file folder", "Objects"),
    ("📊", "bar chart", "Objects"),
    ("📌", "pushpin", "Objects"),
    ("📎", "paperclip", "Objects"),
    ("✂️", "scissors", "Objects"),
    ("✏️", "pencil", "Objects"),
    ("📝", "memo note", "Objects"),
    ("🔍", "magnifying glass search left", "Objects"),
    ("🔎", "magnifying glass search right", "Objects"),
    ("🔒", "locked padlock", "Objects"),
    ("🔓", "unlocked padlock", "Objects"),
    ("🔑", "key", "Objects"),
    ("🗝️", "old key", "Objects"),
    ("🔨", "hammer", "Objects"),
    ("🔧", "wrench", "Objects"),
    ("🔩", "nut and bolt", "Objects"),
    ("⚙️", "gear settings", "Objects"),
    ("🗡️", "dagger", "Objects"),
    ("⚔️", "crossed swords", "Objects"),
    ("🛡️", "shield", "Objects"),
    ("💊", "pill medicine", "Objects"),
    ("💉", "syringe injection", "Objects"),
    ("🧪", "test tube", "Objects"),
    ("🧬", "dna", "Objects"),
    ("🔬", "microscope", "Objects"),
    ("🔭", "telescope", "Objects"),
    ("🔮", "crystal ball", "Objects"),
    ("🪄", "magic wand", "Objects"),
    ("🧲", "magnet", "Objects"),
    ("🪣", "bucket", "Objects"),
    ("🛁", "bathtub", "Objects"),
    ("🚪", "door", "Objects"),
    ("🧹", "broom", "Objects"),
    ("🧺", "basket", "Objects"),
    ("🛋️", "couch and lamp", "Objects"),
    ("🪑", "chair", "Objects"),
    ("🧳", "luggage", "Objects"),
    ("⏰", "alarm clock", "Objects"),
    ("📸", "camera with flash", "Objects"),
    ("📡", "satellite antenna", "Objects"),
    ("🔊", "speaker loud", "Objects"),
    ("🔔", "bell notification", "Objects"),
    ("🎙️", "studio microphone", "Objects"),
    ("📻", "radio", "Objects"),
    ("📺", "television tv", "Objects"),
    ("📠", "fax machine", "Objects"),
    ("🗃️", "card file box", "Objects"),
    ("🗄️", "file cabinet", "Objects"),
    ("🗑️", "wastebasket trash", "Objects"),
    ("🧰", "toolbox", "Objects"),
    ("🪜", "ladder", "Objects"),
    ("💈", "barber pole", "Objects"),
    ("⚗️", "alembic chemistry", "Objects"),
    ("🔭", "telescope astronomy", "Objects"),
    // ── Symbols ───────────────────────────────────────────────────────────
    ("❤️", "red heart love", "Symbols"),
    ("🧡", "orange heart", "Symbols"),
    ("💛", "yellow heart", "Symbols"),
    ("💚", "green heart", "Symbols"),
    ("💙", "blue heart", "Symbols"),
    ("💜", "purple heart", "Symbols"),
    ("🖤", "black heart", "Symbols"),
    ("🤍", "white heart", "Symbols"),
    ("🤎", "brown heart", "Symbols"),
    ("💔", "broken heart", "Symbols"),
    ("❣️", "heart exclamation", "Symbols"),
    ("💕", "two hearts", "Symbols"),
    ("💞", "revolving hearts", "Symbols"),
    ("💓", "beating heart", "Symbols"),
    ("💗", "growing heart", "Symbols"),
    ("💖", "sparkling heart", "Symbols"),
    ("💘", "heart with arrow", "Symbols"),
    ("💝", "heart with ribbon", "Symbols"),
    ("💟", "heart decoration", "Symbols"),
    ("☮️", "peace symbol", "Symbols"),
    ("✝️", "cross", "Symbols"),
    ("☯️", "yin yang", "Symbols"),
    ("✡️", "star of david", "Symbols"),
    ("🆒", "cool button", "Symbols"),
    ("🆓", "free button", "Symbols"),
    ("🆕", "new button", "Symbols"),
    ("🆗", "ok button", "Symbols"),
    ("🆙", "up button", "Symbols"),
    ("🆘", "sos button", "Symbols"),
    ("💯", "hundred points", "Symbols"),
    ("💢", "anger symbol", "Symbols"),
    ("💥", "collision boom", "Symbols"),
    ("💫", "dizzy star", "Symbols"),
    ("💦", "sweat droplets water", "Symbols"),
    ("💨", "dashing away wind", "Symbols"),
    ("💬", "speech balloon", "Symbols"),
    ("💭", "thought balloon", "Symbols"),
    ("✨", "sparkles", "Symbols"),
    ("🌟", "glowing star", "Symbols"),
    ("⭐", "star", "Symbols"),
    ("🔥", "fire flame", "Symbols"),
    ("🎉", "party popper", "Symbols"),
    ("🎊", "confetti ball", "Symbols"),
    ("🎁", "wrapped gift present", "Symbols"),
    ("🎀", "ribbon bow", "Symbols"),
    ("🎈", "balloon", "Symbols"),
    ("✔️", "check mark", "Symbols"),
    ("❌", "cross mark x", "Symbols"),
    ("❗", "exclamation mark", "Symbols"),
    ("❓", "question mark", "Symbols"),
    ("⚠️", "warning", "Symbols"),
    ("🚫", "prohibited no", "Symbols"),
    ("⛔", "no entry", "Symbols"),
    ("♻️", "recycling symbol", "Symbols"),
    ("💎", "gem stone diamond", "Symbols"),
    ("🔔", "bell", "Symbols"),
    ("🔕", "bell with slash", "Symbols"),
    ("📳", "vibration mode", "Symbols"),
    ("📴", "mobile phone off", "Symbols"),
    ("⬆️", "up arrow", "Symbols"),
    ("⬇️", "down arrow", "Symbols"),
    ("➡️", "right arrow", "Symbols"),
    ("⬅️", "left arrow", "Symbols"),
    ("🔀", "shuffle tracks", "Symbols"),
    ("🔁", "repeat button", "Symbols"),
    ("▶️", "play button", "Symbols"),
    ("⏸️", "pause button", "Symbols"),
    ("⏹️", "stop button", "Symbols"),
    ("⏺️", "record button", "Symbols"),
    ("🔴", "red circle", "Symbols"),
    ("🟠", "orange circle", "Symbols"),
    ("🟡", "yellow circle", "Symbols"),
    ("🟢", "green circle", "Symbols"),
    ("🔵", "blue circle", "Symbols"),
    ("🟣", "purple circle", "Symbols"),
    ("⚫", "black circle", "Symbols"),
    ("⚪", "white circle", "Symbols"),
    ("🟤", "brown circle", "Symbols"),
    ("🔶", "large orange diamond", "Symbols"),
    ("🔷", "large blue diamond", "Symbols"),
    ("🔸", "small orange diamond", "Symbols"),
    ("🔹", "small blue diamond", "Symbols"),
    // ── Flags ─────────────────────────────────────────────────────────────
    ("🏳️", "white flag", "Flags"),
    ("🏴", "black flag", "Flags"),
    ("🌈", "rainbow", "Flags"),
    ("🏳️‍🌈", "rainbow flag pride", "Flags"),
    ("🏴‍☠️", "pirate flag", "Flags"),
    ("🇺🇸", "united states flag", "Flags"),
    ("🇬🇧", "united kingdom flag", "Flags"),
    ("🇫🇷", "france flag", "Flags"),
    ("🇩🇪", "germany flag", "Flags"),
    ("🇪🇸", "spain flag", "Flags"),
    ("🇮🇹", "italy flag", "Flags"),
    ("🇯🇵", "japan flag", "Flags"),
    ("🇨🇳", "china flag", "Flags"),
    ("🇧🇷", "brazil flag", "Flags"),
    ("🇨🇦", "canada flag", "Flags"),
    ("🇦🇺", "australia flag", "Flags"),
    ("🇮🇳", "india flag", "Flags"),
    ("🇲🇽", "mexico flag", "Flags"),
    ("🇷🇺", "russia flag", "Flags"),
    ("🇿🇦", "south africa flag", "Flags"),
    ("🇰🇷", "south korea flag", "Flags"),
    ("🇳🇬", "nigeria flag", "Flags"),
    ("🇦🇷", "argentina flag", "Flags"),
    ("🇸🇪", "sweden flag", "Flags"),
    ("🇳🇴", "norway flag", "Flags"),
    ("🇩🇰", "denmark flag", "Flags"),
    ("🇫🇮", "finland flag", "Flags"),
    ("🇵🇹", "portugal flag", "Flags"),
    ("🇳🇱", "netherlands flag", "Flags"),
    ("🇧🇪", "belgium flag", "Flags"),
    ("🇨🇭", "switzerland flag", "Flags"),
    ("🇦🇹", "austria flag", "Flags"),
    ("🇵🇱", "poland flag", "Flags"),
    ("🇺🇦", "ukraine flag", "Flags"),
    ("🇹🇷", "turkey flag", "Flags"),
    ("🇮🇱", "israel flag", "Flags"),
    ("🇸🇦", "saudi arabia flag", "Flags"),
    ("🇳🇿", "new zealand flag", "Flags"),
    ("🇨🇱", "chile flag", "Flags"),
    ("🇨🇴", "colombia flag", "Flags"),
    ("🇵🇭", "philippines flag", "Flags"),
    ("🇮🇩", "indonesia flag", "Flags"),
    ("🇻🇳", "vietnam flag", "Flags"),
    ("🇹🇭", "thailand flag", "Flags"),
    ("🇵🇰", "pakistan flag", "Flags"),
    ("🇧🇩", "bangladesh flag", "Flags"),
    ("🇪🇬", "egypt flag", "Flags"),
    ("🇮🇷", "iran flag", "Flags"),
    ("🇮🇶", "iraq flag", "Flags"),
    ("🇰🇪", "kenya flag", "Flags"),
    ("🇬🇭", "ghana flag", "Flags"),
    ("🇪🇹", "ethiopia flag", "Flags"),
    ("🇨🇿", "czech republic flag", "Flags"),
    ("🇭🇺", "hungary flag", "Flags"),
    ("🇷🇴", "romania flag", "Flags"),
    ("🇬🇷", "greece flag", "Flags"),
    ("🇵🇪", "peru flag", "Flags"),
    ("🇻🇪", "venezuela flag", "Flags"),
    ("🇸🇬", "singapore flag", "Flags"),
    ("🇲🇾", "malaysia flag", "Flags"),
];

/// How many emoji columns fit in the given pixel width.
pub fn emoji_grid_cols(width: f32) -> usize {
    let cell_w = 44.0_f32;
    ((width / cell_w).floor() as usize).max(4)
}
